# docker-compose.yml
version: "3.3"
name: "DDNS Updater"
services:
    update:
        build: .
        restart: unless-stopped
        
        volumes:
            - ./logs:/data/logs
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro