# docker-compose.yml
version: "3.3"
name: "DDNS Updater"
services:
    update:
        build: .
        environment:
          # Timezone
          TZ: "TZ=Australia/Sydney" 
          
        restart: unless-stopped
        
        volumes:
            - ./logs:/data/logs