# docker-compose.yml
version: "3.3"
name: "DDNS Updater"
services:
    update:
        build: .
        environment:
          TTL: ${TTL} # Interval between checks (Default 15 minutes)
          USERNAME: ${USERNAME} # Username for Google DDNS
          PASSWORD: ${PASSWORD} # Password for Google DDNS
          SUBDOMAIN: ${SUBDOMAIN} # Subdomain to update
          DOMAIN: ${DOMAIN} # Domain to update

          TZ: "TZ=Australia/Sydney" # Timezone
          
        restart: unless-stopped
        volumes:
            - ./logs:/data/logs