# TTL for DNS record in seconds
ttl = 900

[[auth_details]]
# Username for Google DDNS
username = "" 
# Password for Google DDNS
password = "" 
# Subdomain to update
subdomain = "" 
# Domain to update
domain = "" 

[[auth_details]]
# Username for Google DDNS
username = ""
# Password for Google DDNS
password = ""
# Subdomain to update
subdomain = ""
# Domain to update
domain = ""